package routers

import (
	"DeepWorkload/controllers"
	"github.com/astaxie/beego"
)

func init() {
	ns := beego.NewNamespace("/api",
		beego.NSRouter("*", &controllers.CommonController{}, "OPTIONS:Options"),
		beego.NSNamespace("/user",
			beego.NSRouter("/getalluserinfobydepartid", &controllers.UserController{}, "post:GetAllUserByDepartId"),
			beego.NSRouter("/checkuserid", &controllers.UserController{}, "post:CheckUserId"),
			beego.NSRouter("/checkmobile", &controllers.UserController{}, "post:CheckMobile"),
			beego.NSRouter("/addoneuser", &controllers.UserController{}, "post:AddOneUser"),
			beego.NSRouter("/edituser", &controllers.UserController{}, "post:EditUser"),
			beego.NSRouter("/deluserinfos", &controllers.UserController{}, "post:DelUsers"),
			beego.NSRouter("/deloneuser", &controllers.UserController{}, "post:DelOneUser"),
			beego.NSRouter("/adduserbyexcel", &controllers.UserController{}, "post:AddUserInfoByExcel"),
			beego.NSRouter("/exportalluser", &controllers.UserController{}, "post:ExportAllUserInfo"),
			beego.NSRouter("/searchuser", &controllers.UserController{}, "post:SearchUser"),
			beego.NSRouter("/addadmin", &controllers.UserController{}, "post:AddAdminUsers"),
			beego.NSRouter("/deloneadmin", &controllers.UserController{}, "post:DelOneAdminUser"),
			beego.NSRouter("/getalladmin", &controllers.UserController{}, "post:GetAllAdminUserInfo"),
			beego.NSRouter("/oneuserdetail", &controllers.UserController{}, "post:GetOneUserInfoDetail"),
			beego.NSRouter("/allusernameandid", &controllers.UserController{}, "post:GetAllUserNameAndUserId"),
			beego.NSRouter("/updatepersonaldata", &controllers.UserController{}, "post:UpdatePersonalData"),
		),
		beego.NSNamespace("/department",
			beego.NSRouter("/adddepartment", &controllers.DepartmentController{}, "post:AddDepartment"),
			beego.NSRouter("/deldepartment", &controllers.DepartmentController{}, "post:DelDepartment"),
			beego.NSRouter("/editdepartment", &controllers.DepartmentController{}, "post:EditDepartment"),
			beego.NSRouter("/getalldepartment", &controllers.DepartmentController{}, "post:GetAllDepartment"),
			beego.NSRouter("/getalldepartmentanduser", &controllers.DepartmentController{}, "post:GetAllDepartmentAndUser"),
		),
		beego.NSNamespace("/type",
			beego.NSRouter("/addone", &controllers.TypeController{}, "post:AddOneType"),
			beego.NSRouter("/getallbytype", &controllers.TypeController{}, "post:GetAllTypeByTypeDesc"),
			beego.NSRouter("/editone", &controllers.TypeController{}, "post:EditOneTypeName"),
			beego.NSRouter("/delone", &controllers.TypeController{}, "post:DelTypeById"),
		),
		beego.NSNamespace("/common",
			beego.NSRouter("/uploadfiles", &controllers.CommonController{}, "post:UploadFile"),
			beego.NSRouter("/uploadimages", &controllers.CommonController{}, "post:UploadImageBase64"),
			beego.NSRouter("/qiniutoken", &controllers.CommonController{}, "get:GetQiNiuToken"),
			beego.NSRouter("/qiniudown", &controllers.CommonController{}, "post:QiNiuDownloadUrlByKey"),
		),
		beego.NSNamespace("/form",
			beego.NSRouter("/addonetemplateform", &controllers.FormInfoController{}, "post:AddOneTemplateForm"),
			beego.NSRouter("/getalltemplateform", &controllers.FormInfoController{}, "post:GetTemplateFormInfo"),
			beego.NSRouter("/gettemplateformdetail", &controllers.FormInfoController{}, "post:GetTemplateFormDetail"),
			beego.NSRouter("/deltemplateform", &controllers.FormInfoController{}, "post:DelTemplateForm"),
			beego.NSRouter("/edittitle", &controllers.FormInfoController{}, "post:EditName"),
			beego.NSRouter("/edittype", &controllers.FormInfoController{}, "post:EditType"),
			beego.NSRouter("/updatecooper", &controllers.FormInfoController{}, "post:UpdateTemplateCooperation"),
			beego.NSRouter("/checkformula", &controllers.FormInfoController{}, "post:CheckEnableFormulaMethod"),
			beego.NSRouter("/getallformbytypeid", &controllers.FormInfoController{}, "post:GetAllFormInfoByTypeId"),
			beego.NSRouter("/getallauthorizetemplateform", &controllers.FormInfoController{}, "post:GetAuthorizeTemplateFormInfo"),
			beego.NSRouter("/getallauthorizeformbytypeid", &controllers.FormInfoController{}, "post:GetAllAuthorizeFormInfoByTypeId"),
			beego.NSRouter("/getallformtree", &controllers.FormInfoController{}, "post:TemplateFormTree"),
			beego.NSRouter("/getallopentemplateform", &controllers.FormInfoController{}, "post:GetOpenTemplateFormInfo"),
			beego.NSRouter("/installopentemplateform", &controllers.FormInfoController{}, "post:OpenTemplateInstall"),
			beego.NSRouter("/getallopenformbytypeid", &controllers.FormInfoController{}, "post:GetAllOpenFormInfoByTypeId"),
		),
		beego.NSNamespace("/task",
			beego.NSRouter("/createonetask", &controllers.TaskController{}, "post:CreateOneTask"),
			beego.NSRouter("/gettaskfullinfo", &controllers.TaskController{}, "post:GetTaskFullInfo"),
			beego.NSRouter("/alltaskinfo", &controllers.TaskController{}, "post:AllTaskInfoByCorpId"),
			beego.NSRouter("/getallclosedtaskbyuserid", &controllers.TaskController{}, "post:GetAllClosedTaskInfoByUserId"),
			beego.NSRouter("/getalltaskbyuserid", &controllers.TaskController{}, "post:GetAllTaskInfoByUserId"),
			beego.NSRouter("/getallauthorizetaskbyuserid", &controllers.TaskController{}, "post:GetAllAuthorizeTaskInfo"),
			beego.NSRouter("/getalltaskbytypeid", &controllers.TaskController{}, "post:GetAllTaskInfoByTypeID"),
			beego.NSRouter("/getallauthorizetaskbytypeid", &controllers.TaskController{}, "post:GetAllAuthorizeTaskInfoByTypeID"),
			beego.NSRouter("/selfcreatesearch", &controllers.TaskController{}, "post:SearchSelfCreate"),
			beego.NSRouter("/authorizesearch", &controllers.TaskController{}, "post:SearchAuthorize"),
			beego.NSRouter("/switchtaskstate", &controllers.TaskController{}, "post:SwitchTaskState"),
			beego.NSRouter("/deltask", &controllers.TaskController{}, "post:DelTask"),
			beego.NSRouter("/updatescope", &controllers.TaskController{}, "post:UpdateScope"),
			beego.NSRouter("/getreporttask", &controllers.TaskController{}, "post:GetReportTaskListByUserId"),
			beego.NSRouter("/getreportedtask", &controllers.TaskController{}, "post:GetReportedTaskListByUserId"),
			beego.NSRouter("/getreportedtaskbytypeid", &controllers.TaskController{}, "post:GetReportedTaskInfoByTypeID"),
			beego.NSRouter("/getformlist", &controllers.TaskController{}, "post:GetFormList"),
			beego.NSRouter("/getaudformlist", &controllers.TaskController{}, "post:GetAuditFormList"),
			beego.NSRouter("/getselfformlist", &controllers.TaskController{}, "post:GetSelfTaskFormList"),
			beego.NSRouter("/getformdetail", &controllers.TaskController{}, "post:GetFormDetail"),
			beego.NSRouter("/checkisauditor", &controllers.TaskController{}, "post:CheckAuditMissionByUserId"),
			beego.NSRouter("/getallaudittaskbyuserid", &controllers.TaskController{}, "post:GetAllAuditTaskByUserId"),
			beego.NSRouter("/getexceltemplate", &controllers.TaskController{}, "post:DownLoadExcelTemplate"),
			beego.NSRouter("/addmaindatabyexcel", &controllers.TaskController{}, "post:AddMainDatasByExcel"),
		),
		beego.NSNamespace("/pubtask",
			beego.NSRouter("/getpubinfo", &controllers.PubTaskController{}, "post:GetPublicInfoByCode"),
			beego.NSRouter("/updatepubinfo", &controllers.PubTaskController{}, "post:UpdateTaskPublicInfo"),
			beego.NSRouter("/allpubtask", &controllers.PubTaskController{}, "post:GetAllPubTask"),
			beego.NSRouter("/allpubdata", &controllers.PubTaskController{}, "post:GetAllPubMainData"),
		),

		beego.NSNamespace("/maindata",
			beego.NSRouter("/counttempfunction", &controllers.MainDataController{}, "post:CountTempFunction"),
			beego.NSRouter("/countfunction", &controllers.MainDataController{}, "post:CountFunction"),
			beego.NSRouter("/addone", &controllers.MainDataController{}, "post:AddOneMainData"),
			beego.NSRouter("/adminaddone", &controllers.MainDataController{}, "post:AdminAddOneMainData"),
			beego.NSRouter("/allmaindatabyformcodeanduserid", &controllers.MainDataController{}, "post:GetAllMainDataByFormCodeAndTaskCode"),
			beego.NSRouter("/allmaindatabyformcodeandaudituserid", &controllers.MainDataController{}, "post:GetAllMainDataByFormCodeAndTaskCodeAndAdu"),
			beego.NSRouter("/delone", &controllers.MainDataController{}, "post:DelOneMainData"),
			beego.NSRouter("/batchdel", &controllers.MainDataController{}, "post:DelMainDatas"),
			beego.NSRouter("/edit", &controllers.MainDataController{}, "post:EditOneMainDataDetail"),
			beego.NSRouter("/detailbycode", &controllers.MainDataController{}, "post:GetOneMainDataDetail"),
			beego.NSRouter("/getauditlist", &controllers.MainDataController{}, "post:GetAuditList"),
			beego.NSRouter("/commitmaindatawithoutaudit", &controllers.MainDataController{}, "post:CommitMainDataWithOutAudit"),
			beego.NSRouter("/batchcommitmaindatawithoutaudit", &controllers.MainDataController{}, "post:BatchCommitMainDataWithOutAudit"),
			beego.NSRouter("/commitmaindatawithnodecode", &controllers.MainDataController{}, "post:CommitMainDataWithNodeCode"),
			beego.NSRouter("/batchcommitmaindatawithnodecode", &controllers.MainDataController{}, "post:BatchCommitMainDataWithNodeCode"),
			beego.NSRouter("/commitmaindatawithtask", &controllers.MainDataController{}, "post:CommitMainDataWithTask"),
			beego.NSRouter("/batchcommitmaindatawithtask", &controllers.MainDataController{}, "post:BatchCommitMainDataWithTask"),
			beego.NSRouter("/callbackone", &controllers.MainDataController{}, "post:CallBackOneMainData"),
			beego.NSRouter("/alltoauditelist", &controllers.MainDataController{}, "post:GetAllToAuditedMainData"),
			beego.NSRouter("/allhaveauditedlist", &controllers.MainDataController{}, "post:GetAllHaveAuditedMainData"),
			beego.NSRouter("/approveone", &controllers.MainDataController{}, "post:ApproveOneMainData"),
			beego.NSRouter("/approvemaindatas", &controllers.MainDataController{}, "post:ApproveMainDatas"),
			beego.NSRouter("/denyone", &controllers.MainDataController{}, "post:DenyOneMainData"),
			beego.NSRouter("/denymaindatas", &controllers.MainDataController{}, "post:DenyMainDatas"),
			beego.NSRouter("/getallloginfobydatacode", &controllers.MainDataController{}, "post:GetAllLogByDataCode"),
			beego.NSRouter("/checkaudittype", &controllers.TaskController{}, "post:CheckTaskAuditType"),
			beego.NSRouter("/othertoselfassigndata", &controllers.MainDataController{}, "post:AssignDataOtherToSelf"),
			beego.NSRouter("/count", &controllers.MainDataController{}, "post:GetCountByTaskCodeAndFormCode"),
			beego.NSRouter("/fsearch", &controllers.DataAnalysis{}, "post:Search"),
		),

		beego.NSNamespace("/gather",
			beego.NSRouter("/gatherlist", &controllers.GatherController{}, "post:GatherListByTaskCode"),
			beego.NSRouter("/export", &controllers.GatherController{}, "post:ExportExcel"),
			beego.NSRouter("/gatherlistbyuserid", &controllers.GatherController{}, "post:GatherListByTaskCodeAndUserId"),
			beego.NSRouter("/gatherlistaudit", &controllers.GatherController{}, "post:GatherListByTaskCodeAndAuditUserId"),
			beego.NSRouter("/exportaudit", &controllers.GatherController{}, "post:ExportExcelByAuditUserId"),
		),

		beego.NSNamespace("/login",
			beego.NSRouter("/signin", &controllers.LoginController{}, "post:Login"),
			beego.NSRouter("/signup", &controllers.LoginController{}, "post:SignUp"),
			beego.NSRouter("/checkmobile", &controllers.LoginController{}, "post:CheckMobile"),
			beego.NSRouter("/ssyzm", &controllers.LoginController{}, "post:GetGUID"),
			beego.NSRouter("/checkyzm", &controllers.LoginController{}, "post:CheckYanZM"),
			beego.NSRouter("/checkad", &controllers.LoginController{}, "post:CheckAdmin"),
			beego.NSRouter("/sendsms", &controllers.LoginController{}, "post:SendVerifySMS"),
			beego.NSRouter("/checkmobileyzm", &controllers.LoginController{}, "post:CheckMobileVerify"),
			beego.NSRouter("/loginbymobile", &controllers.LoginController{}, "post:LoginByMobile"),
			beego.NSRouter("/setpassswd", &controllers.LoginController{}, "post:SetPasswd"),

			beego.NSRouter("/getopenid", &controllers.LoginController{}, "post:GetOpenId"),
			beego.NSRouter("/unbinduser", &controllers.LoginController{}, "post:UnbindUser"),
			beego.NSRouter("/openidtouserid", &controllers.LoginController{}, "post:OpenidToUserid"),
		),

		beego.NSNamespace("/market",
			beego.NSRouter("/alltype", &controllers.MarketController{}, "post:GetAllType"),
			beego.NSRouter("/addonetype", &controllers.MarketController{}, "post:AddOneType"),
			beego.NSRouter("/editonetype", &controllers.MarketController{}, "post:EditOneType"),
			beego.NSRouter("/delonetype", &controllers.MarketController{}, "post:DelOneType"),
			beego.NSRouter("/alltemplate", &controllers.MarketController{}, "post:GetAllMarketTemplate"),
			beego.NSRouter("/addtemplate", &controllers.MarketController{}, "post:AddOneMarketTemplateForm"),
			beego.NSRouter("/activetemplate", &controllers.MarketController{}, "post:ActiveFormCode"),
			beego.NSRouter("/deltemplate", &controllers.MarketController{}, "post:DelOneTemplate"),
			beego.NSRouter("/login", &controllers.MarketController{}, "post:MarketLogin"),
			beego.NSRouter("/gettemplateformdetail", &controllers.MarketController{}, "post:GetTemplateFormDetail"),
			beego.NSRouter("/counttempfunction", &controllers.MarketController{}, "post:CountFunction"),
		),
		beego.NSNamespace("/charts",
			beego.NSRouter("/dependencies", &controllers.DataAnalysis{}, "post:Dependencies"),
		),
	)
	beego.AddNamespace(ns)
	RouterFilter()
}
